services:
  api:
    build:
      context: ./app
      dockerfile: ../docker/Dockerfile
    container_name: lab-api-sre
    # Note que removemos o "ports" daqui. 
    # Agora sรณ o Nginx fala com o mundo externo.
    restart: always

  nginx:
    image: nginx:alpine
    container_name: lab-proxy-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    restart: always