services:
  api:
    build:
      context: ./app        # O Docker agora "entra" na pasta app para buildar
      dockerfile: ../docker/Dockerfile
    container_name: lab-api-sre
    ports:
      - "8000:8000"
    restart: always